apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: vendelux-localkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        sha: ba5615aaef44
    spec:
      containers:
        - name: api
          image: image:tag
          envFrom:
            - configMapRef:
                name: config-api
            - secretRef:
                name: secret-api
