apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vendelux-localkube
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      name: http-port
      port: 8080
      targetPort: 8080
